import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import nextImagen from "../public/next-js.png";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <h1> <Image src={nextImagen} width={"100"} height={"100"} alt="Imagen de Next.js" /> Mi Sitio Web</h1>
        
        <div style={{border: "5px solid white"}}>
        {children}
        </div>
      </body>
    </html>
  );
}
